import {
  CategoryResponseType,
  DepartementResponseType,
} from "@crema/types/models/master";

const masterDepartementData: DepartementResponseType[] = [
  {
    id: 1,
    name: "Teknik",
    code: "TNK",
    modifyStatus: "I",
    createdTime: "2023-10-10T21:22:43.560Z",
    createdBy: null,
    lastModifiedTime: "2023-10-10T21:22:43.560Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 23, 161],
    },
  },
  {
    id: 2,
    name: "Agronomi",
    code: "AGR",
    modifyStatus: "I",
    createdTime: "2023-10-10T21:23:05.840Z",
    createdBy: null,
    lastModifiedTime: "2023-10-10T21:23:05.840Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 23, 163],
    },
  },
  {
    id: 3,
    name: "Budget and Control",
    code: "BNC",
    modifyStatus: "I",
    createdTime: "2023-10-10T21:23:32.960Z",
    createdBy: null,
    lastModifiedTime: "2023-10-10T21:23:32.960Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 23, 165],
    },
  },
  {
    id: 4,
    name: "Human Resource",
    code: "HRD",
    modifyStatus: "I",
    createdTime: "2023-10-10T22:24:29.463Z",
    createdBy: null,
    lastModifiedTime: "2023-10-10T22:24:29.463Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 23, 174],
    },
  },
  {
    id: 5,
    name: "Finance",
    code: "FNC",
    modifyStatus: "I",
    createdTime: "2023-10-17T23:12:27.453Z",
    createdBy: 2,
    lastModifiedTime: "2023-10-17T23:12:27.453Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 39, 36],
    },
  },
  {
    id: 6,
    name: "Taxes",
    code: "TXS",
    modifyStatus: "I",
    createdTime: "2023-10-17T23:18:04.897Z",
    createdBy: 2,
    lastModifiedTime: "2023-10-17T23:18:04.897Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 39, 42],
    },
  },
  {
    id: 7,
    name: "Sipil",
    code: "CIVI",
    modifyStatus: "I",
    createdTime: "2023-10-17T23:23:22.640Z",
    createdBy: 2,
    lastModifiedTime: "2023-10-17T23:23:22.640Z",
    lastModifiedBy: null,
    rowVersion: {
      type: "Buffer",
      data: [0, 0, 0, 0, 0, 0, 39, 48],
    },
  },
];

const masterCategoryData: CategoryResponseType[] = [
  {
    id: 1,
    name: "Item Kerja Panen",
    departmentCode: "AGR",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 2,
    name: "BJR",
    departmentCode: "AGR",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 3,
    name: "Rumah Rusak",
    departmentCode: "TNK",
    modifyStatus: "U",
    lastModifiedBy: null,
  },
  {
    id: 5,
    name: "Kesehatan",
    departmentCode: "HRD",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 6,
    name: "Timbangan Rusak",
    departmentCode: "AGR",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 7,
    name: "Karyawan Cabut",
    departmentCode: "AGR",
    modifyStatus: "U",
    lastModifiedBy: 2,
  },
  {
    id: 8,
    name: "Karyawan Sakit terus",
    departmentCode: "HRD",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 9,
    name: "Karyawan Cabut",
    departmentCode: "HRD",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
  {
    id: 10,
    name: "Category1",
    departmentCode: "AGR",
    modifyStatus: "I",
    lastModifiedBy: null,
  },
];

export { masterDepartementData, masterCategoryData };
